### ISSUE TITLE
Perhaps consider the use of a code formatter - specifically Black

### ISSUE THREAD

**Issue by Solomon1732** [gursi26/virtual_drawing_board#10]
Black is an automatic code formatter. While not necessarily fit for everyone's taste, it's PEP8 compliant, can be configured, and has a few additional defaults which can result in a cleaner code. This ensures a uniform coding convention across commits.

https://pypi.org/project/black/

Edit: it also automates the formatting process, so there's less overhead when writing code. It reduces the need to make the code aesthetic and PEP8 compliant.

**Comment by gursi26** [comment]
Thanks. I will look into it.
