### ISSUE TITLE
Creating a GUI 

### ISSUE THREAD

**Issue by gursi26** [gursi26/virtual_drawing_board#11]
Creating a simple GUI to allow for easier user interaction. Could include functions such as the following:
- Allow users to change pen colour.
- Allow users to change the thickness of the pen.
- Allow users to save their drawings as an image file.

**Comment by Jibendu007** [comment]
@gursi26  can i be assigned to this?

**Comment by gursi26** [comment]
Hi! I have assigned you this issue.

**Comment by daksh10110** [comment]
Hey, can you assign me this issue?

 I can do first two, I need to think about what to do in the third part.

**Comment by neerajanand321** [comment]
Hey, I want to work on this issue,  Please assign it to me.
