### ISSUE TITLE
Improving the smoothness of drawing

### ISSUE THREAD

**Issue by gursi26** [gursi26/virtual_drawing_board#12]
The draw function currently detects whether the user's hand is in the "draw" position (only index finger sticking out) and stores the coordinates of the tip of the user's index finger. These coordinates are stored in a list.

In every frame, a blue circle is drawn at each coordinate in the list of coordinates. Due to technical constraints, the program runs at approximately 15-20 FPS and therefore, when the user moves their hand in one quick motion, the line ends up being disjointed, as seen in the image below.

<img width="1269" alt="demo" src="https://user-images.githubusercontent.com/75204369/135747896-e99219d3-5bd8-4ba3-bc6a-0ea3e11b12f6.png">

This can be fixed with a function that checks if points drawn in two consecutive frames are far apart, and then appends the coordinate list with a set of intermediate points in between the far apart points.

**Comment by git12121** [comment]
Hi, could you assign me to this?

**Comment by git12121** [comment]
> This can be fixed with a function that checks if points drawn in two consecutive frames are far apart, and then appends the coordinate list with a set of intermediate points in between the far apart points.

I've implemented this but there's a lot of issues which I've mentioned on PR #15
