### ISSUE TITLE
PEP8 Linter

### ISSUE THREAD

**Issue by git12121** [gursi26/virtual_drawing_board#16]
I think it would make it easier to contribute if there was a standardized code style.
For example, on line 93 (of `main.py`) there is whitespace before the colon while on line 115 there isn't:
![image](https://user-images.githubusercontent.com/28541089/135758182-f904bc04-9a29-48de-806a-a4abac1563d9.png)
(The latter would be considered the correct one according to [PEP8](http://pep8online.com/))

**Comment by gursi26** [comment]
Thanks. I'll look into using a code formatter after other issues have been resolved (to avoid conflicts while merging forks).
