### ISSUE TITLE
how to use data_collection.py to create new action?

### ISSUE THREAD

**Issue by Trueman1997** [gursi26/virtual_drawing_board#21]
good job!

I want to create some new action with hand tracking,
it seems use data_collection.py to collect gestures datasets,then train the model.

but I do not know how use the code to collect datasets , could you give me some advice?
thanks a lot!

**Comment by Trueman1997** [comment]
help!
@gursi26

**Comment by gursi26** [comment]
The data_collection.py script outputs all three coordinates (x,y,z) of each of the 21 landmarks to a csv file. While creating the dataset, I ran it multiple times, once for each action (draw, erase and do nothing), inputting the action name [here](https://github.com/gursi26/virtual_drawing_board/blob/fb7dbc192d8875983282d2f312d134f21d6e596c/dataset/data_collection.py#L57). I then used concat.py to merge all csv files into one larger csv file for training the model. 

When running data_collection.py, the cv2 module will use your live camera feed along with mediapipe's hand pose estimation model to collect the set of coordinates that correspond to the specified action at each frame that the video feed captures. I would simply hold a hand up in the particular pose, move it around the screen to ensure the model has a variety of data to work with, and then quit the program with Ctrl-C.

**Comment by Trueman1997** [comment]
> 

I ran data_collection.py,input the name of action that I want to create("cut"),and then hold the particular pose in front of the camera.After that ,I pressed Ctrl-C in order to quit,but it did not work. I had to terminate the program,and there was no csv file saved....
could u tell me what's wrong?

C:\Users\admin\anaconda3\python.exe F:/project_11.25/virtual_drawing_board-main/dataset/data_collection.py
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Enter action name : cut

Process finished with exit code -1

**Comment by Trueman1997** [comment]
When you run the program and after demonstrating the gesture, pressed ctrl-c to exit, will there be a dataset of the gesture saved?

I did what you say,but it did not work. I do not konw what's the problem?
@gursi26

**Comment by gursi26** [comment]
I have just tested it out, and it seems to be working for me. A csv file for the new gesture is created in the same directory where data_collection.py is.

When you run the program and the cv2 window shows up, are you able to see the landmarks with connecting points drawn on your hand? This indicates that mediapipe is working. If not, try collecting data in well lit area.

**Comment by Trueman1997** [comment]
when I run the program,I input the action name in the Terminal and pressed Enter,then the cv2 windows appeared,I can see the landmarks in the cv2 window,and I hold up the gesture in front of the camera in order to collect dataset,**but the problem is that I do not konw how to quit.**
**when I pressed ctrl-c, the program and cv2 window was still working and csv file did not saved.**
So I had to stop the program and I can not get the csv file.
@gursi26

**Comment by Trueman1997** [comment]
I pressed ctrl-c in order to quit the program after collecting dataset,but it seemed do not work.
Are you sure the program can be closed with **ctrl-c**?
@gursi26

**Comment by Trueman1997** [comment]
when you finish collecting the dataset,how do you **quit**? By pressing **ctrl-c**? It did not work for me,the program was still working and I can not get the csv file. @gursi26

**Comment by Trueman1997** [comment]
Did I miss something?

**Comment by Trueman1997** [comment]
I have solven the problem of data collection,thanks a lot!
