### ISSUE TITLE
Train problem

### ISSUE THREAD

**Issue by Trueman1997** [gursi26/virtual_drawing_board#22]
I have collected my gesture dataset and I want to **train my own model**.
I have some probem about the code "self.map = {'draw': 1, 'erase': 0}" in train.ipynb.
Now I have collected **seven gestures** and they have been put together in one csv file。if I want to train my own gesture model , how do I change this line of code"self.map = {'draw': 1, 'erase': 0}",and where will the trained model be stored? @gursi26

**Comment by Trueman1997** [comment]
I just wanted to retrain the model with the dataset that you provided(draw,erase,none),but it seemed appear some probelm about dataload, could you give me advice? thanks a lot! @gursi26 


EPOCH :  0
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13788/570704198.py in <module>
     10     total_loss = 0
     11 
---> 12     for x,y in loader :
     13         opt.zero_grad()
     14         yhat = model.forward(x)

~\anaconda3\lib\site-packages\torch\utils\data\dataloader.py in __next__(self)
    515             if self._sampler_iter is None:
    516                 self._reset()
--> 517             data = self._next_data()
    518             self._num_yielded += 1
    519             if self._dataset_kind == _DatasetKind.Iterable and \

~\anaconda3\lib\site-packages\torch\utils\data\dataloader.py in _next_data(self)
    555     def _next_data(self):
    556         index = self._next_index()  # may raise StopIteration
--> 557         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    558         if self._pin_memory:
    559             data = _utils.pin_memory.pin_memory(data)

~\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py in fetch(self, possibly_batched_index)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~\AppData\Local\Temp/ipykernel_13788/1519802275.py in __getitem__(self, index)
      6 
      7     def __getitem__(self,index):
----> 8         yvals = torch.tensor([self.map[self.dataset[index][1]]], dtype=torch.float)
      9         xvals = torch.from_numpy(self.dataset[index][2:].astype(np.float32))
     10         return xvals,yvals

KeyError: 0.833501995

**Comment by gursi26** [comment]
Hi. I have updated the training script in the most recent commit. It appears the previous training script was outdated and only took into account 2 gestures (draw and erase) rather than 3 (draw, erase and none), thereby leading to the KeyError. It should work now.

**Comment by Trueman1997** [comment]
> Hi. I have updated the training script in the most recent commit. It appears the previous training script was outdated and only took into account 2 gestures (draw and erase) rather than 3 (draw, erase and none), thereby leading to the KeyError. It should work now.

it works! thanks a lot!
so if I want train my own model, I need to change **"self.map = {'draw': 0, 'erase': 1, 'none': 2}"** and the path of dataset.
For example,now I have a new dataset which includes 5 gestures,so I need to change the code to "self.map = {'draw': 0, 'erase': 1, 'none': 2,'xxx':3,'yyy':4}" and replace old dataset with my new dataset,then train the model.
Is it right？ @gursi26

**Comment by gursi26** [comment]
Yes, that is right.
