### ISSUE TITLE
Modify the README.md file

### ISSUE THREAD

**Issue by kriptonian1** [gursi26/virtual_drawing_board#3]
# Stylize the ` README.md` file and give it a professional look
- Format heading
-  Add badges

**Comment by kriptonian1** [comment]
@gursi26 can I work on this for `Hacktoberfest`

**Comment by gursi26** [comment]
Hi! Yes feel free to contribute. I'll add the Hacktoberfest tag to the project shortly.

**Comment by kriptonian1** [comment]
okey, thanks

**Comment by kriptonian1** [comment]
Does this look good
![image](https://user-images.githubusercontent.com/74916308/135071495-0d7e72a5-7c35-4611-b285-d1e5b76bfadf.png)

**Comment by gursi26** [comment]
Yea that looks great! Small thing though it looks like you misspelled PyTorch in the bar above. Other than that is is pretty good!

**Comment by kriptonian1** [comment]
Added some more stuff, just want to ask will it be fine if I remove `Camera demo` word
![image](https://user-images.githubusercontent.com/74916308/135075469-8862614f-f8b7-43ff-bdf6-42d23603a9c4.png)

**Comment by gursi26** [comment]
Hi! Yea it looks great. You can make any changes you feel are necessary and then PR. Thanks for your contribution.

**Comment by kriptonian1** [comment]
Happy to Contribute in this amazing project

**Comment by kriptonian1** [comment]
can you pls tag this issue as `hacktoberfest`

**Comment by gursi26** [comment]
Alright, I have labelled the issue.
