### ISSUE TITLE
`0xFF == ord('q')` is always false. Unclear what it does in the if-statement

### ISSUE THREAD

**Issue by Solomon1732** [gursi26/virtual_drawing_board#5]
The if-statement holds a condition which is always false. It is unclear what it does there. Since it's an operand for an `and` operator, this means the condition is always false as a whole.

https://github.com/gursi26/virtual_drawing_board/blob/b521fce24d8043f564e91bca3d32716073a12c3e/main.py#L145

**Comment by Solomon1732** [comment]
I just noticed there's also this exact line in another file (linked below):
https://github.com/gursi26/virtual_drawing_board/blob/b521fce24d8043f564e91bca3d32716073a12c3e/dataset/data_collection.py#L82

**Comment by gursi26** [comment]
`0xFF == ord('q')` checks if the "q" character is pressed to close the video feed. This particular if statement is commonly used while accessing videos using the OpenCV module.

**Comment by Solomon1732** [comment]
I see. Closing the bug.
